// MIRROR PROTOCOL: Deployment Constants
// Data is fetched from GitHub Raw URL in production to ensure real-time updates without redeploys.

export const GITHUB_RAW_BASE = "https://raw.githubusercontent.com/ananyapgit/arbitrage-bot/main/dashboard-new/public/data";

export const getApiUrl = (endpoint: string) => {
  // Mapping of endpoints to static JSON files generated by tools/generate_dashboard_data.py
  const mapping: Record<string, string> = {
    "/api/dashboard/stats": "/stats.json",
    "/api/dashboard/deals": "/deals.json",
    "/api/dashboard/categories": "/categories.json",
    "/api/dashboard/heatmap": "/heatmap.json",
    "/api/dashboard/subscribers/recent": "/subscribers_recent.json",
  };

  const file = mapping[endpoint] || endpoint;

  if (process.env.NODE_ENV === "production") {
    // Append a timestamp to bypass cache and prevent potential 403/404 on stale files
    const ts = new Date().getTime();
    return `${GITHUB_RAW_BASE}${file}?t=${ts}`;
  }
  
  return `/data${file}`;
};
